# Generated by Django 5.1.6 on 2025-03-10 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shower', '0001_initial'),
        ('user', '0002_user_password_alter_user_phonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showerStarted', models.DateTimeField(verbose_name='When the shower has started')),
                ('showerFinished', models.DateTimeField(verbose_name='When the shower has finished')),
                ('shower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shower.shower')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
