# Generated by Django 5.1.6 on 2025-02-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('user', 'User')], max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('firstName', models.CharField(max_length=30)),
                ('genre', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], null=True)),
                ('age', models.PositiveBigIntegerField()),
                ('phoneNumber', models.PositiveBigIntegerField(max_length=12)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('showerPerWeek', models.IntegerField(max_length=2)),
                ('timePerShower', models.TimeField()),
                ('fingerPrint', models.CharField(max_length=254)),
                ('createdAt', models.DateField()),
                ('status', models.IntegerField(choices=[(1, 'Activated'), (0, 'Deactivated')])),
            ],
        ),
    ]
