# Generated by Django 5.1.6 on 2025-02-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='1234', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='showerPerWeek',
            field=models.IntegerField(),
        ),
    ]
