# Generated by Django 5.1.6 on 2025-03-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shower_per_week',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_per_shower',
            field=models.DurationField(default='00:10:00'),
        ),
    ]
